version: 2

references:
  workspace: &workspace
    /tmp/proteus-spring
  cache_key: &cache_key
    v1-proteus-spring-{{ checksum "/tmp/todaysdate" }}
  container_config: &container_config
    working_directory: *workspace
    docker:
      - image: circleci/openjdk:8-jdk-browsers
  install_protoc: &install_protoc
    run:
      name: "Install Protoc"
      command: |
        sudo apt-get update -y; sudo apt-get install software-properties-common -y
        sudo add-apt-repository ppa:maarten-fonville/protobuf -y
        sudo apt-get update -y
        sudo apt-get install libprotobuf-dev libprotoc-dev protobuf-compiler -y --allow-unauthenticated

jobs:
  build:
    <<: *container_config
    steps:
      - run:
          name: "setup date file"
          command: date +%D > /tmp/todaysdate
      - restore_cache:
          key: *cache_key
      - *install_protoc
      - checkout
      - run:
          name: Build
          command: './gradlew clean build'
      - run:
          name: ensure no gradle lock
          command: |
            rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
      - save_cache:
          key: *cache_key
          paths:
              - ~/.gradle/caches/
              - ~/.gradle/wrapper/
              - ~/.m2"
      - persist_to_workspace:
          root: *workspace
          paths:
            - .
  deploy:
    <<: *container_config
    steps:
      - attach_workspace:
        at: *workspace
      - run:
          name: Deploy
          command: './gradlew -PreleaseType=release -PbintrayUser="${bintrayUser}" -PbintrayKey="${bintrayKey}" bintrayUpload --stacktrace'
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          context: bintray
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
